import assert from 'node:assert/strict';
import { readFile, mkdir } from 'node:fs/promises';
import { createServer } from 'node:http';
import { fileURLToPath } from 'node:url';
import { resolve, extname } from 'node:path';
import { createRequire } from 'node:module';
import { selectProjects } from './project-order.mjs';
import { recommendNextAction } from './action-rules.mjs';
const { chromium } = createRequire(import.meta.url)('playwright');
const root = fileURLToPath(new URL('../', import.meta.url));
const real = JSON.parse(await readFile(resolve(root,'data/papers.json'),'utf8'));
const fixture = structuredClone(real);
fixture.papers = Array.from({length:5}, (_,i)=> ({...structuredClone(real.papers[0]), id:`test-${i}`,title:`Alpha Project ${i}`, shortCode:`Project ${i}`, focusStage:'writing',statusCode:'manuscript_writing',statusStartedAt:'2026-08-01',statusTimeline:[],startedAt:'2025-01-01',updatedAt:`2026-10-0${i+1}`,priority:['low','medium','high','medium','high'][i],pinned:i===0,showInAttention:true,nextAction:i===1?'我的自定义行动':'',nextDue:['2026-10-01','','2026-10-20','2026-10-20',''][i],submissions:[{journal:'Test Journal',status:'under_review',statusStartedAt:'2026-08-01',statusEndedAt:'',submittedAt:'2026-07-20',customMetadata:'preserve me'}]}));
fixture.papers[2].focusStage='submission'; fixture.papers[2].statusCode='under_review';
fixture.papers[3].focusStage='submission'; fixture.papers[3].statusCode='revision_1';
fixture.papers[4].startedAt='2026-05-01';
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{
  const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);
  const path=resolve(root,'.'+(pathname==='/'?'/index.html':pathname));
  if(!path.startsWith(root)){res.writeHead(403).end();return;}
  try{res.setHeader('Content-Type',mime[extname(path)]||'text/plain');res.end(await readFile(path));}catch{res.writeHead(404).end();}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}/`;
let browser;
let activePage;
const errors=[];
const output=process.env.TEST_ARTIFACTS_PATH || resolve(root,'test-artifacts');
await mkdir(output,{recursive:true});
try {
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--single-process','--no-zygote','--no-sandbox']}: {})});
  const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',permissions:['clipboard-read','clipboard-write']});
  await context.route(/fonts\.(googleapis|gstatic)\.com/,route=>route.abort());
  const page=await context.newPage();
  activePage=page;
  page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install({time:new Date('2026-10-08T04:30:00Z')});
  await page.goto(url); await page.waitForSelector('.paper-card');
  assert.equal(await page.locator('.paper-card').count(),real.papers.length);
  await page.locator('.paper-title-button').first().click();
  assert.equal(await page.locator('#paperDialog [name=focusStage]').count(),0,'Reading mode has no edit fields');
  assert.equal(await page.locator('#savePaperButton').isVisible(),false);
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>localStorage.getItem('paperflow-draft-v1')),null);
  await page.route('**/data/papers.json',route=>route.fulfill({json:fixture}));
  await page.reload(); await page.waitForSelector('.paper-card');
  const displayed=()=>page.locator('#paperList .paper-card').evaluateAll(nodes=>nodes.map(n=>n.dataset.paperId));
  const draft=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('paperflow-draft-v1')));
  const open=id=>page.locator(`[data-paper-id="${id}"] .paper-title-button`).click();
  const field=name=>page.locator(`#paperDialog [name="${name}"]`);
  const save=()=>page.locator('#savePaperButton').click();
  const close=()=>page.locator('#paperDialog [data-close-paper]').first().click();
  const focus=await page.locator('[data-focus-open]').getAttribute('data-focus-open');
  const attention=await page.locator('[data-attention-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.attentionId));
  for(const sort of ['custom','priority','deadline','updated','started']) {
    await page.locator('#sortSelect').selectOption(sort);
    assert.deepEqual(await displayed(),selectProjects(fixture.papers,{sort}).map(p=>p.id),`${sort} displayed order`);
    assert.equal(await page.locator('[data-focus-open]').getAttribute('data-focus-open'),focus);
    assert.deepEqual(await page.locator('[data-attention-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.attentionId)),attention);
  }
  await page.locator('#sortSelect').selectOption('priority');
  assert.deepEqual(await displayed(),['test-2','test-4','test-1','test-3','test-0']);
  await page.locator('#searchInput').fill('Project'); await page.locator('#stageFilter').selectOption('writing');
  assert.deepEqual(await displayed(),['test-4','test-1','test-0']);
  await page.locator('#searchInput').fill('nothing matches'); assert.equal(await page.locator('.paper-card').count(),0);
  await page.locator('#searchInput').fill(''); await page.locator('#stageFilter').selectOption('all');
  await page.locator('#toggleManageButton').click(); await page.locator('#sortSelect').selectOption('custom');
  // Native browser drag: before target; then verify local draft, sorting and reload.
  const targetCard = page.locator('[data-paper-id="test-3"]');
  await targetCard.scrollIntoViewIfNeeded();
  const targetBox = await targetCard.boundingBox();
  await page.locator('[data-paper-id="test-4"] .drag-handle').dragTo(targetCard,{targetPosition:{x:targetBox.width/2,y:targetBox.height/3}});
  assert.deepEqual(await displayed(),['test-0','test-1','test-2','test-4','test-3']);
  const custom=await displayed();
  await page.locator('#sortSelect').selectOption('updated'); await page.locator('#sortSelect').selectOption('custom');
  assert.deepEqual(await displayed(),custom);
  await page.reload(); await page.waitForSelector('.paper-card'); assert.deepEqual(await displayed(),custom);
  await page.locator('#toggleManageButton').click();
  await page.locator('#sortSelect').selectOption('priority');
  await page.locator('[data-priority-id="test-0"]').selectOption('high');
  assert.deepEqual(await displayed(),['test-0','test-2','test-4','test-1','test-3']);
  await open('test-0');
  assert.equal(await field('nextAction').inputValue(),recommendNextAction('writing','manuscript_writing'));
  await field('focusStage').selectOption('submission');
  assert.equal(await field('statusCode').inputValue(),'under_review');
  assert.equal(await field('nextAction').inputValue(),recommendNextAction('submission','under_review'));
  assert.equal(await field('nextDue').inputValue(),'2026-10-01','Recommendation must leave deadline unchanged');
  await field('priority').selectOption('high'); await field('progress').fill('60'); await save();
  let stored=(await draft()).papers.find(p=>p.id==='test-0');
  assert.equal(stored.statusTimeline.length,1); assert.equal(stored.statusTimeline[0].endedAt,'2026-10-08');
  assert.equal(stored.statusStartedAt,'2026-10-08'); assert.equal(stored.nextActionAuto,stored.nextAction);
  assert.equal(stored.submissions[0].customMetadata,'preserve me'); assert.equal(stored.submissions[0].submittedAt,'2026-07-20');
  await open('test-0'); await save();
  assert.equal((await draft()).papers.find(p=>p.id==='test-0').statusTimeline.length,1);
  await open('test-0'); await field('statusCode').selectOption('revision_1');
  assert.equal(await field('nextAction').inputValue(),recommendNextAction('submission','revision_1'));
  await field('nextAction').fill('手动填写的新行动'); await field('statusCode').selectOption('decision_pending');
  assert.equal(await field('nextAction').inputValue(),'手动填写的新行动');
  await page.locator('#keepActionButton').click(); await save();
  assert.equal((await draft()).papers.find(p=>p.id==='test-0').nextActionAuto,undefined);
  await open('test-1'); await field('focusStage').selectOption('submission');
  assert.equal(await field('nextAction').inputValue(),'我的自定义行动');
  await page.locator('#applyActionButton').click(); assert.equal(await field('nextAction').inputValue(),recommendNextAction('submission','under_review'));
  await field('statusEffectiveAt').fill('2026-07-01'); await save();
  assert.equal(await page.locator('#paperDialog').isVisible(),true);
  assert.equal((await draft()).papers.find(p=>p.id==='test-1').focusStage,'writing');
  await field('statusEffectiveAt').fill('2026-10-08'); await save();
  // Closing must never save edits; cleared fields must survive reload.
  await open('test-1'); await field('nextAction').fill('不要保存'); await close();
  assert.notEqual((await draft()).papers.find(p=>p.id==='test-1').nextAction,'不要保存');
  await open('test-1'); await field('nextAction').fill(''); await field('nextDue').fill(''); await save();
  await page.reload(); await page.waitForSelector('.paper-card');
  assert.equal((await draft()).papers.find(p=>p.id==='test-1').nextAction,'');
  await page.locator('#toggleManageButton').click();
  // Every entry opens the same single dialog.
  await page.locator('#openAllPapersButton').click(); await page.locator('[data-all-paper-id="test-1"]').click();
  assert.equal(await page.locator('dialog[open]').count(),1); assert.equal(await field('focusStage').count(),1); await close();
  await page.locator('[data-focus-open]').click(); assert.equal(await field('focusStage').count(),1); await close();
  await page.locator('[data-attention-id]').first().click(); assert.equal(await field('focusStage').count(),1); await close();
  await page.locator('#addPaperButton').click();
  await field('title').fill('New Project'); await field('shortCode').fill('NEW'); await field('focusStage').selectOption('publication');
  await save(); assert.equal((await draft()).papers.at(-1).statusTimeline.length,0);
  await page.locator('#searchInput').fill('New Project'); assert.equal(await page.locator('.paper-card').count(),1);
  const newId=(await displayed())[0]; await open(newId);
  await page.locator('#paperDialog summary').filter({hasText:'Advanced Settings'}).click();
  page.once('dialog',d=>d.accept()); await page.locator('#deletePaperButton').click();
  assert.equal((await draft()).papers.length,5); await page.locator('#searchInput').fill('');
  // Backup round-trip and publish preparation; no GitHub write or deployment.
  await page.locator('#openToolsButton').click();
  const downloadEvent=page.waitForEvent('download'); await page.locator('#exportButton').click();
  const download=await downloadEvent; const exported=JSON.parse(await readFile(await download.path(),'utf8'));
  await page.locator('#importInput').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
  assert.deepEqual((await draft()).papers,exported.papers);
  await page.locator('#headerPublishButton').click(); assert.equal(await page.locator('dialog[open]').count(),1);
  assert.equal(await page.locator('#githubEditLink').getAttribute('href'),'https://github.com/shj0512/paperflow-hub/edit/main/data/papers.json');
  await page.locator('#copyDataButton').click();
  assert.deepEqual(JSON.parse(await page.evaluate(()=>navigator.clipboard.readText())).papers,exported.papers);
  await page.locator('#closePublishButton').click();
  await page.locator('#projects').scrollIntoViewIfNeeded(); await page.screenshot({path:resolve(output,'desktop-projects.png')});
  await open('test-0'); await page.screenshot({path:resolve(output,'desktop-panel.png')});
  await page.keyboard.press('Tab'); assert.equal(await page.evaluate(()=>!!document.activeElement.closest('#paperDialog')),true);
  await page.keyboard.press('Escape'); assert.equal(await page.locator('dialog[open]').count(),0);
  // Tablet and phone layout; real browser measurements and interactions.
  for (const width of [768,390,320]) {
    await page.setViewportSize({width,height:844});
    const overflow = await page.evaluate(() => [...document.querySelectorAll('body *')].filter(el => {
      const box=el.getBoundingClientRect();return box.width && (box.right>innerWidth+1 || box.left < -1) && getComputedStyle(el).visibility!=='hidden';
    }).map(el=>`${el.tagName}.${el.className}`).slice(0,20));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Page overflow at ${width}: ${overflow.join(', ')}`);
    await page.locator('#sortSelect').selectOption('custom');
    const before=await displayed(); await page.locator(`[data-move-id="${before[1]}"][data-move-direction="-1"]`).click();
    assert.equal((await displayed())[0],before[1]);
    await open('test-0');
    assert.ok(await page.locator('#paperDialog').evaluate(el=>el.scrollWidth<=el.clientWidth),`Panel overflow at ${width}`);
    await field('statusCode').selectOption('revision_2'); await field('nextDue').fill('2026-11-01');
    await field('priority').selectOption('medium'); await save();
    assert.equal((await draft()).papers.find(p=>p.id==='test-0').nextDue,'2026-11-01');
    await open('test-0');
    if(width===390) await page.screenshot({path:resolve(output,'mobile-panel.png')});
    await close();
  }
  await page.locator('#toggleManageButton').click(); await open('test-0');
  assert.equal(await field('focusStage').count(),0); assert.equal(await page.locator('#savePaperButton').isVisible(),false);
  assert.deepEqual(errors,[],'No unhandled page errors');
  console.log('Browser regression passed: rendered sorting/filtering, drag/draft/reload, unified cross-stage editing, recommendations/manual protection, history/CRUD, import/export/publish preparation, keyboard, desktop/tablet/phone layouts and Reading Mode.');
} catch(error) { if(activePage) { await activePage.screenshot({path:resolve(output,'failure.png'),fullPage:true}).catch(()=>{}); console.log('PAGE ERRORS:',errors); } throw error; } finally { await browser?.close(); await new Promise(r=>server.close(r)); }
